### ISSUE TITLE
Tray icon changes accodring to status

### ISSUE THREAD

**Issue by smaragdus** [toxygen-project/toxygen#10]
The user can the change status via tray control so it would be nice if the tray icon reflects status- a tiny green/yellow/red dot in the key-hole, similar to qTox for example.

An option to auto-set status to "Away" after a user-defined period of inactivity will also be nice,

**Comment by ingvar1995** [comment]
1. I don't like qTox tray icon but it isn't too difficult to add this feature. But I think it should be done easily using plugins
2. There are 2 ways to do it. IIRC qTox sets status "Away" when you are out from app for some time. That's easy solution but not correct. So it ends with https://github.com/tux3/qTox/issues/3327 etc. The second way is to handle keyboard and mouse events. That's impossible for qt and really bad idea for cross-platform app but not for platform-specific plugin.

**Comment by ingvar1995** [comment]
I implemented auto away status for Windows as plugin ([link](https://github.com/ingvar1995/toxygen_plugins/tree/master/AutoAwayStatusWindows)). I hope once Toxygen will get its own unique icon, so tray icon with status should be done via plugins only. If you want you can ask for it in main [plugins repo](https://github.com/ingvar1995/toxygen_plugins). I'm closing this as not client issue.
