### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by azlux** [toxygen-project/toxygen#12]
Hi,
I'm giving a try to toxygen, and it's look great.
I have one issue. Into setting, utf-8 is available, but when we go back in the friend list, the utf-8 characters aren't. (look at my status)

![capture](https://cloud.githubusercontent.com/assets/11210117/17396904/d501a462-5a35-11e6-9ba2-d1e6b3dcb27b.JPG)

**Comment by ingvar1995** [comment]
Fixed in 99f31cc
