### ISSUE TITLE
smooth picture and font

### ISSUE THREAD

**Issue by azlux** [toxygen-project/toxygen#13]
Hi again,
For the avatars, we can clearly see that the pictures is resized but not smooth. (compare the capture with my github picture profile)
![capture](https://cloud.githubusercontent.com/assets/11210117/17403251/36d8e058-5a57-11e6-9932-25934aec3e6e.JPG)

I think Qt have already smooth function for picture (not sure about that)

For the font, I think we can found a better one, specially when you choose a small size (I know qtox use a monospace font)

**Comment by ingvar1995** [comment]
I will try to add possibility to choose font.

**Comment by ingvar1995** [comment]
Avatars:  3a64121
Do you want to set font of messages only?

**Comment by azlux** [comment]
it's depend. It is a big work to change font on everything ? It will be weird to have specific font for messages and another one for the rest of the GUI.
I just think the default one isn't the best one we can have for chatting.

**Comment by ingvar1995** [comment]
> It is a big work to change font on everything

No

> It will be weird to have specific font for messages and another one for the rest of the GUI.

Right now font for settings isn't set. I gonna fix it too

**Comment by azlux** [comment]
so i think it's better to change it for everything

**Comment by ingvar1995** [comment]
Fonts added in  b0e82df
