### ISSUE TITLE
Close to tray

### ISSUE THREAD

**Issue by azlux** [toxygen-project/toxygen#14]
For chatting program, we don't really want it to be close, so the close button is for close the program to tray and not for exit it.
It's an habit to close a program, i forgot that toxygen will be close.
I think this improvement can be a default option into Settings.

Azlux

**Comment by ingvar1995** [comment]
Use 'Esc' button (#6)

>I think this improvement can be a default option into Settings.

![comics-owlturd-gui-usability-1267472](https://cloud.githubusercontent.com/assets/10050680/17409830/7937a1f6-5a79-11e6-8a2a-cd2fba5834a0.png)

**Comment by ingvar1995** [comment]
'Close to tray' option added in  b0e82df

**Comment by smaragdus** [comment]
@ingvar1995 
This is cute, thanks! ;)
I know that "Esc" minimizes Toxygen but yet I can't remember how many time i exited it (close button) influenced by my habits with other messengers.
I do appreciate this new option!

**Comment by smaragdus** [comment]
I see that there is a new release (0.2.4) but I can't find the Windows version.

**Comment by ingvar1995** [comment]
It will be added in ~30 mins

**Comment by smaragdus** [comment]
@ingvar1995 
Thanks in advance,
When I come back tonight I will test it.
Regards
