### ISSUE TITLE
Video sending on Windows

### ISSUE THREAD

**Issue by ingvar1995** [toxygen-project/toxygen#16]
[Sending video frame](https://github.com/toxygen-project/toxygen/blob/video/toxygen/toxav.py#L283) on Windows fails with errors like 'Access to 0x00000000' or 'Wrong parameter type', Tested on Python 3.3 - 3.5. It can be wrapper bug (I think not), **ctypes bug** (looks like it) or broken libtox.dll (but other clients use it without problems).  On Ubuntu it works fine. I can't continue video calls without fix. Right now I'm no idea what to do. :disappointed:

**Comment by smaragdus** [comment]
**@ingvar1995**

I read that 

> ...video calls and group chats development is blocked now.

No real progress in that area?

Thank you for version 0.2.6, it is running just fine on Windows (8).

**Comment by ingvar1995** [comment]
>No real progress in that area?

No. Video is blocked by this bug on Windows - wrapper still doesn't work and I don't know why. I need more time to understand how to deal with it but I don't have enough time :disappointed: And if it is python bug it will be difficult to find solution. About gc - I implemented minimal support for both old and new gc but new gc still not ready and old gc are waste, so I don't see any reason to continue.
