### ISSUE TITLE
AUR package doesn't install in $PATH

### ISSUE THREAD

**Issue by Sorunome** [toxygen-project/toxygen#17]
When installing the toxygen-git AUR package I had to manually create the file /usr/bin/toxygen with the following:
```
#!/bin/bash
python3 /opt/toxygen/toxygen/main.py "$@"
```

**Comment by ingvar1995** [comment]
@quininer

**Comment by quininer** [comment]
You should comment [here](https://aur.archlinux.org/packages/toxygen-git/). :)

solve:
https://aur.archlinux.org/cgit/aur.git/commit/?h=toxygen-git&id=24fc813b1253d3bf5748365696417f910321d51c

**Comment by ingvar1995** [comment]
Thanks, @quininer
