### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by Sorunome** [toxygen-project/toxygen#23]
Toxygen has some timezone stuff off......

example:
```
sorunome@sorunome-desktop ~ $ date -u
Tue Aug 30 16:31:11 UTC 2016
sorunome@sorunome-desktop ~ $ date
Tue Aug 30 18:31:12 CEST 2016

```
While toxygen displays as 17:31

```
sorunome@sorunome-desktop ~ $ ls -l /etc/localtime
lrwxrwxrwx 1 root root 33 Dec  3  2014 /etc/localtime -> /usr/share/zoneinfo/Europe/Berlin
```

**Comment by ingvar1995** [comment]
For all messages? Try in termainal: 
python3
import time
print(time.strftime('%H:%M'))
Does it show current time?

**Comment by Sorunome** [comment]
Yes, for all messages. Manually running pythons time function does display the correct time as expected.

**Comment by ingvar1995** [comment]
Does it show incorrect time right after message appearance or later, after switching friends?

**Comment by Sorunome** [comment]
On both, all the time

**Comment by ingvar1995** [comment]
Can you try:
```
import time
t = time.time()
sec = int(t) - time.timezone
m, s = divmod(sec, 60)
h, m = divmod(m, 60)
d, h = divmod(h, 24)
s = '%02d:%02d' % (h, m)
print(s)
```

**Comment by Sorunome** [comment]
That gives the weird time which toxygen displays, the one that is one hour off from the correct one.

**Comment by Sorunome** [comment]
The issue seems to me being time.timezone here, it seems to be ignoring sumer / wintertime, time.timezone returns -3600 for me, while during the sumertime we are actually 2h away from UTC, not just 1h

**Comment by ingvar1995** [comment]
Yes, timezone produces error. What about
```
import time
t = time.time()
offset = time.timezone if (time.localtime().tm_isdst == 0) else time.altzone
sec = int(t) + offset
m, s = divmod(sec, 60)
h, m = divmod(m, 60)
d, h = divmod(h, 24)
s = '%02d:%02d' % (h, m)
print(s)
```

**Comment by Sorunome** [comment]
That is even more off.

time.daylight appears to be return 1 if there are currently daylight saving times, which means it requires an additional hour offset.

According to the docs time.timezone only gives the offset without daylight saving time

**Comment by ingvar1995** [comment]
offset = time.timezone if not time.daylight else time.timezone - 3600 should fix this bug

**Comment by Sorunome** [comment]
why not

offset = time.timezone - time.daylight*3600

**Comment by ingvar1995** [comment]
Also good if time.daylight is int

**Comment by Sorunome** [comment]
It appears to be int

**Comment by ingvar1995** [comment]
Fixed in develop
