### ISSUE TITLE
new-message bubble

### ISSUE THREAD

**Issue by Sorunome** [toxygen-project/toxygen#25]
The new-message bubble in the lower-right corner of a friends avatar in the friendlist is all-white and there is no number inside indicating how many new messages there are.

**Comment by ingvar1995** [comment]
Try to change its color in interface settings

**Comment by Sorunome** [comment]
Ah, yeah, that is it.

So the bug here is then actually that in the settings it defaults to white no matter what, so when clicking through the settings and playing arround i accidentally set it to white. IMO the expected result should be that the color picker should default to whatever value it was at previously.

Also I hope i'm not annoying you with too many bug reports :S

**Comment by ingvar1995** [comment]
Default color in settings is red.

**Comment by Sorunome** [comment]
Well, every time i open the color picker it is at white, but it should be at whichever color it was set to...

**Comment by ingvar1995** [comment]
Yeah, you are right
