### ISSUE TITLE
Toxygen updater

### ISSUE THREAD

**Issue by azlux** [toxygen-project/toxygen#27]
Hi
I think there are some improvement for the update you can add to the project.
- [x] Toxygen update notification on start
- [x] Propose the user to download the new version
- [x] Auto-install

The main feature for now is the notification i think. This way we don't need to check the GitHub repository every day for upgrade.

Azlux

**Comment by Renha** [comment]
you could start Watching repository for not checking github every day

**Comment by ingvar1995** [comment]
Updater code is available [here](https://github.com/toxygen-project/toxygen_updater)
Toxygen will support updates after next release. I'm closing this because updater is ready and moved to separated repo.
