### ISSUE TITLE
Could not load non-toxygen profile

### ISSUE THREAD

**Issue by Renha** [toxygen-project/toxygen#28]
[that could be Arch package issue, but still]

toxygen don't even try to create missing config files.

just installed toxygen and tried to load profile. It worked only after:
https://gist.github.com/Renha/23b3b4b5f8d50faffff30e37a65aecfd

**Comment by ingvar1995** [comment]
Fixed in  9fe9ba4

**Comment by Renha** [comment]
Thank you, now error only when "set as default profile" checked.
```
Traceback (most recent call last):
  File "/opt/toxygen/toxygen/main.py", line 462, in <module>
    main()
  File "/opt/toxygen/toxygen/main.py", line 458, in main
    toxygen.main()
  File "/opt/toxygen/toxygen/main.py", line 149, in main
    Settings.set_auto_profile(path, name)
  File "/opt/toxygen/toxygen/settings.py", line 64, in set_auto_profile
    with open(p) as fl:
FileNotFoundError: [Errno 2] No such file or directory: '/home/renha/.config/tox/toxygen.json'
```

**Comment by ingvar1995** [comment]
Should be fixed.Do you use toxygen from latest develop branch?

**Comment by Renha** [comment]
i'll check again later, thank you
