### ISSUE TITLE
Closing to tray on systems without PySide tray support

### ISSUE THREAD

**Issue by Renha** [toxygen-project/toxygen#29]
At first run, toxygen greets me with lying, it says:
"Press Esc if you want hide app to tray."

ok, that's not exactly lie (it doesn't says that app WILL hide to tray), but I still don't have any tray, and after pressing Esc window is gone, but app is still running in terminal and don't react to ctrl+c.

**Comment by Renha** [comment]
oh, sorry, it is reacting to ctrl+c:

```
libpng warning: iCCP: known incorrect sRGB profile
^Cfgcgfg
^C^C^C^C^C^C^C^C^C^[Traceback (most recent call last):
  File "/opt/toxygen/toxygen/mainscreen.py", line 93, in event
    def event(self, event):
KeyboardInterrupt
```

but still running.

**Comment by ingvar1995** [comment]
So tray icon doesn't appear?

**Comment by Renha** [comment]
Yes, of course, I don't have any tray - so I don't have any tray icon either

**Comment by ingvar1995** [comment]
You don't have tray - where do you want to see tray icon? What do you expect from app?

**Comment by ingvar1995** [comment]
After  006b3cd app cannot be closed to tray if tray isn't available
