### ISSUE TITLE
Add shutdown handler

### ISSUE THREAD

**Issue by azlux** [toxygen-project/toxygen#30]
Hi,
Small improvement idea here.
I propose to add a system shutdown trigger. Some people don't close all open programs when they shutdown the computer and toxygen will open a popup alert that the program wasn't closed properly at the next startup.

I know they are already some triggers for a system like QtGui.QApplication.aboutToQuit.connect() function.
What do you think ?

Azlux

**Comment by ingvar1995** [comment]
Yeah, closing on shutdown is good idea. I added support for it. Will close this issue after testing
