### ISSUE TITLE
underrun occurred

### ISSUE THREAD

**Issue by kamnxt** [toxygen-project/toxygen#32]
When in-call, I only hear a kind of buzzing sound, and I get this message repeatedly in the output:

    ALSA lib pcm.c:8251:(snd_pcm_recover) underrun occurred
    ALSA lib pcm.c:8251:(snd_pcm_recover) underrun occurred
    ALSA lib pcm.c:8251:(snd_pcm_recover) underrun occurred
    ALSA lib pcm.c:8251:(snd_pcm_recover) underrun occurred
    ALSA lib pcm.c:8251:(snd_pcm_recover) underrun occurred

Running Arch Linux, built from AUR package. Also, video calling doesn't seem to work.

**Comment by ingvar1995** [comment]
1) This is known ALSA bug. You can try ``export PULSE_LATENCY_MSEC=60`` in terminal before running Toxygen. Or try solution like [this](https://bbs.archlinux.org/viewtopic.php?id=185736)
2) Video calls is not yet implemented. One bug stopped implementing this feature for a while
I'm closing this as not really client issue
