### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by rugk** [toxygen-project/toxygen#34]
Debian Jessie here:

```console
$ sudo apt-get install -t jessie-backports toxygen 
[…]
Die folgenden zusätzlichen Pakete werden installiert [WILL BE INSTALLED]:
  libphonon4 libpyside-py3-1.2 libshiboken-py3-1.2 libtoxav0 libtoxcore0 libtoxencryptsave0 phonon
  phonon-backend-vlc python3-pyaudio python3-pyside python3-pyside.phonon python3-pyside.qtcore
  python3-pyside.qtdeclarative python3-pyside.qtgui python3-pyside.qthelp python3-pyside.qtnetwork
  python3-pyside.qtopengl python3-pyside.qtscript python3-pyside.qtsql python3-pyside.qtsvg
  python3-pyside.qttest python3-pyside.qtuitools python3-pyside.qtwebkit python3-pyside.qtxml
  vlc-plugin-pulse
Vorgeschlagene Pakete [SUGGESTED]:
  phonon-backend-gstreamer phonon-backend-mplayer python-pyaudio-doc
Die folgenden NEUEN Pakete werden installiert [NEW PACKAGES]:
  libphonon4 libpyside-py3-1.2 libshiboken-py3-1.2 libtoxav0 libtoxcore0 libtoxencryptsave0 phonon
  phonon-backend-vlc python3-pyaudio python3-pyside python3-pyside.phonon python3-pyside.qtcore
  python3-pyside.qtdeclarative python3-pyside.qtgui python3-pyside.qthelp python3-pyside.qtnetwork
  python3-pyside.qtopengl python3-pyside.qtscript python3-pyside.qtsql python3-pyside.qtsvg
  python3-pyside.qttest python3-pyside.qtuitools python3-pyside.qtwebkit python3-pyside.qtxml
  toxygen vlc-plugin-pulse
[…]
$ toxygen                     
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/toxygen/libtox.py", line 16, in __init__
    self._libtoxcore = CDLL('libtoxcore.so')
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtoxcore.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/toxygen", line 9, in <module>
    load_entry_point('Toxygen==0.2.7.0', 'console_scripts', 'toxygen')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/toxygen/main.py", line 3, in <module>
    import profile
  File "/usr/lib/python3/dist-packages/toxygen/profile.py", line 1, in <module>
    from list_items import *
  File "/usr/lib/python3/dist-packages/toxygen/list_items.py", line 8, in <module>
    from file_transfers import TOX_FILE_TRANSFER_STATE, PAUSED_FILE_TRANSFERS, DO_NOT_SHOW_ACCEPT_BUTTON, ACTIVE_FILE_TRANSFERS, SHOW_PROGRESS_BAR
  File "/usr/lib/python3/dist-packages/toxygen/file_transfers.py", line 5, in <module>
    from tox import Tox
  File "/usr/lib/python3/dist-packages/toxygen/tox.py", line 34, in <module>
    class Tox:
  File "/usr/lib/python3/dist-packages/toxygen/tox.py", line 36, in Tox
    libtoxcore = LibToxCore()
  File "/usr/lib/python3/dist-packages/toxygen/libtox.py", line 18, in __init__
    self._libtoxcore = CDLL(util.curr_directory() + '/libs/libtoxcore.so')
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3/dist-packages/toxygen/libs/libtoxcore.so: cannot open shared object file: No such file or directory

$ apt-cache show toxygen          
Package: toxygen
Version: 0.2.7-1
Architecture: amd64
Maintainer: Yann Prive <encrypt@encrypt-tips.tk>
Installed-Size: 5516
Depends: python3, libtoxcore0, libtoxav0, libtoxencryptsave0, python3-pyside, python3-pyaudio
Homepage: https://github.com/toxygen-project/toxygen
Priority: optional
Section: net
Filename: pool/jessie/t/toxygen/toxygen_0.2.7-1_amd64.deb
Size: 2557452
SHA256: ffaa57e0743cc3d35cd9bf6e7838c7d2574627148e97d175ca2987527a563a68
SHA1: 9f1e310f6b4725464bfdbf843e46ee2e4ac9303d
MD5sum: 521662c15f02e4733a6c689597006e4d
Description: Tox client
 Powerful Tox client written in pure Python3.
Description-md5: 1aa5dda4cbd57d77fe5d60d59bdeb41d

Package: toxygen
Version: 0.2.6-1
Architecture: amd64
Maintainer: Yann Prive <encrypt@encrypt-tips.tk>
Installed-Size: 5515
Depends: python3, libtoxcore0, libtoxav0, libtoxencryptsave0, python3-pyside, python3-pyaudio
Homepage: https://github.com/toxygen-project/toxygen
Priority: optional
Section: net
Filename: pool/jessie/t/toxygen/toxygen_0.2.6-1_amd64.deb
Size: 2560456
SHA256: fde664251f0533b53ab246c6b75c5509f73abc56f43e26867a486a90967f5585
SHA1: a668bbf4ea37615b7baf3ee408c3a44e21d5aef5
MD5sum: b2869e1870ce3a9532735e93a22ac21e
Description: Tox client
 Powerful Tox client written in pure Python3.
Description-md5: 1aa5dda4cbd57d77fe5d60d59bdeb41d
```

**Comment by ingvar1995** [comment]
@encrypt what is wrong with packages, on some systems toxygen can't find toxcore.

**Comment by rugk** [comment]
Strange.
I also installed toxcore-dev right now, but the same error is displayed.

```console
$ apt-cache show libtoxcore-dev
Package: libtoxcore-dev
Source: libtoxcore
Version: 0.1.3769.dcf2aaa-1
Architecture: amd64
Maintainer: tux3 <barrdetwix@gmail.com>
Installed-Size: 457
Depends: libtoxcore0 (= 0.1.3769.dcf2aaa-1), libsodium-dev
Homepage: https://tox.chat
Priority: extra
Section: libdevel
Filename: pool/jessie/libt/libtoxcore/libtoxcore-dev_0.1.3769.dcf2aaa-1_amd64.deb
Size: 116496
SHA256: c7ad43a2c92a72c4bae956a6caca9bece008e77297a0453b97513469d6a8ec88
SHA1: b7ffd247c9e02e690378977e0b0279739c894ac7
MD5sum: 770a961f32ee5f0677ef80acd43f841a
Description: distributed, secure messenger w/ a/v support - core development headers
 Tox provides an encrypted, distributed, and extensible peer-to-peer platform
 that can be used for various forms of communication. Tox is intended to be used
 as a multimedia messenger, but many people have shown us that Tox can be used
 for a lot more than just instant messaging.
 .
 This package contains the core development headers.
Description-md5: 875d25d207da308dcff16a2a768e2fe0
```

**Comment by ingvar1995** [comment]
Probably it was installed in wrong directory. Toxygen reqiures libtoxcore.so in /usr/lib/. Check if libtoxcore.so is here. If it is in /usr/local/lib/ try sudo ldconfig

**Comment by rugk** [comment]
Here is the output from the package:
```shell
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libtoxcore.so.0
/usr/lib/x86_64-linux-gnu/libtoxcore.so.0.0.0
/usr/share
/usr/share/doc
/usr/share/doc/libtoxcore0
/usr/share/doc/libtoxcore0/changelog.Debian.gz
/usr/share/doc/libtoxcore0/copyright
```

So the file actually is in `/usr/lib/x86_64-linux-gnu`. After running `sudo ldconfig` the file is *not* symblinked to `/usr/lib`.

In any case toxygen should know were that file is saved as the packes are the official tox.chat ones, so they know the paths and can even change them if necessary.
x64 here BTW.

**Comment by ingvar1995** [comment]
Toxygen tries to find libtoxcore.so in libs default directory (/usr/libs/ on most systems). In you case libtoxcore not in path (why?) so toxygen cannot find it. Have you tried to export path to libtoxcore before running toxygen?

**Comment by rugk** [comment]
> In you case libtoxcore not in path (why?)
Maybe because of the x64 version is installed?

It is maybe just the wrong architecture: https://askubuntu.com/questions/52617/what-is-usr-lib-i386-linux-gnu-for
https://askubuntu.com/questions/449348/why-are-boost-package-libs-installed-to-usr-lib-x86-64-linux-gnu

After reinstalling it via purge & `apt-get install libtoxcore0` now, it is still there:
```console
$ l *tox*            
lrwxrwxrwx 1 root   19 Okt 31 01:51 libtoxcore.so.0 -> libtoxcore.so.0.0.0
-rw-r--r-- 1 root 233K Okt 31 01:51 libtoxcore.so.0.0.0
```

**Comment by ingvar1995** [comment]
>wrong architecture: 

Probably.

What about ``export LD_LIBRARY_PATH="/path/to/libtoxcore/"`` before running toxygen?

**Comment by rugk** [comment]
> What about export LD_LIBRARY_PATH="/path/to/libtoxcore/" before running toxygen?

That's a workaround. This does not fix the underlying problem.

**Comment by ingvar1995** [comment]
But it helps? If smth is wrong with package arch I'm not sure that it will help...

**Comment by rugk** [comment]
It should not be wrong. Either the package must be corrected or toxygen should search in the correct path.
In case you are tghe developer (you're only listed as a contributor on GitHub, maybe make yourself public in the toxygenm-prject organisation) you should ask the tox.chat guys why the lib is saved where it is/why this is the library.

**Comment by ingvar1995** [comment]
>Toxygen should search in the correct path.

Unfortunately, it cannot be done (python doesn't support this). Also there is a problem in using 32-bit toxcore and 64-bit python or 64-bit toxcore and 32-bit python. Does any of available packages works on your machine? Probably once I will use OBS for packages but I'm the only one contributor now and I'm too busy to do it in close future.

**Comment by rugk** [comment]
Please don't use OBS, tox.chat is really fine, but that packages (of tox core) would you recommend to install?

**Comment by ingvar1995** [comment]
I can recommend to install toxcore manually. Cannot recommend packages because I didn't test them all.

**Comment by Encrypt** [comment]
Hello! Sorry for the delay, I've been very busy recently.
So, I've read this thread and I don't really know what can be done here.

First, regarding your command @rugk (`$ sudo apt-get install -t jessie-backports toxygen`), note that we do not use the backports repository. So, one of the problems could be that you have packages which are "too new", breaking the way toxygen works.

Now, having a look at the Traceback, I can see that Toxygen tries to find toxcore at: `/usr/lib/python3/dist-packages/toxygen/libs/libtoxcore.so`.
This is definitely wrong, since toxcore is available at: `/usr/lib/x86_64-linux-gnu/libtoxcore.so.0`
So, there is probably something wrong in the code, I can see in the Traceback: `self._libtoxcore` = CDLL(util.curr_directory() + '/libs/libtoxcore.so')`.
I guess this line has to be reviewed.

Finally, note @Ingvar1995 that clients are switching to Toktok/c-toxcore.
So, when you have time, don't hesitate to switch to that version of toxcore.

**Comment by ingvar1995** [comment]
> I can see in the Traceback: self._libtoxcore = CDLL(util.curr_directory() + '/libs/libtoxcore.so')`.

**Comment by ingvar1995** [comment]
@Encrypt any updates on this?

**Comment by Encrypt** [comment]
Nope, I'm afraid I can't do much here...
I guess you should implement different approaches to load toxcore, depending on the OS.

**Comment by ingvar1995** [comment]
Unfortunately I'm limited by Python. Not sure that smth can be done here. On shindows Python can load toxcore by path but on Linux it doesn't work. I will try to find a hack to avoid this problem.

**Comment by ffamousffatman** [comment]
Walkaround i was doing last night after short research:
`cd /usr/lib/python3/dist-packages/toxygen/
sudo mkdir libs
cd
sudo ln -s /usr/lib/x86_64-linux-gnu/libtoxcore.so.0.0.0 /usr/lib/python3.5/dist-packages/toxygen/libs/libtoxcore.so
sudo ln -s /usr/lib/x86_64-linux-gnu/libtoxencryptsave.so.0.0.0 /usr/lib/python3.5/dist-packages/toxygen/libs/libtoxencryptsave.so`

**Comment by ingvar1995** [comment]
What about libtoxav?

**Comment by ffamousffatman** [comment]
Toxygen was not calling me for libautoxav absence.
`sudo ln -s /usr/lib/x86_64-linux-gnu/libtoxav.so.0.0.0 /usr/lib/python3.5/dist-packages/toxygen/libs/libtoxav.so`
And so, and so, I presume.

**Comment by ingvar1995** [comment]
@Encrypt are packages for toxygen still supported?

**Comment by Encrypt** [comment]
Hello!

Yes, toxygen packages are still supported.

However, most clients have switched to libtoxcore-toktok
I have recently been looking for you on IRC to ask you whether I should switch toxygen to that new toxcore too?

I'll do it during the week-end if you wish so! :smiley:

**Comment by ingvar1995** [comment]
Toxygen use old toxcore api. Once I will have time I will implement toktok support too. Btw develop branch now requires opencv installed - do you have any ideas how to thiis dep to packages?

**Comment by Encrypt** [comment]
It should be as simple as adding this dependency in the "toxygen" config file of ToxDeb!
I'll have a look this week-end!

**Comment by ingvar1995** [comment]
Not sure that OpenCV can be installed in so simple way. Also there are a lot of updates: I migrated from PySide to PyQt5 (package python3-pyqt5) and also need python numpy module. Video calls require a lot of deps :cry:

**Comment by Fak3** [comment]
I just installed toxygen with `sudo pip3 install toxygen` on openSUSE and got exactly the same error. toxygen version installed is 0.2.7.0 
libtoxcore is installed in `/usr/lib64`:
```
u1@pc1:~> rpm -ql libtoxcore1 
/usr/lib64/libtoxcore.so.1
/usr/lib64/libtoxcore.so.1.9.0
```

**Comment by ingvar1995** [comment]
For manual/pip installation it's ok because toxygen can't locate toxcore that isn't in path. That's why I recommended to install toxcore into /usr/lib in installation instructions. But for packages this behavior is not accesible because users expect everything working perfectly after package installation.

**Comment by Fak3** [comment]
> For manual/pip installation it's ok because toxygen can't locate toxcore that isn't in path.

How this is ok? Other packages installed with pip can perfectly find libs in standard library paths which includes `/usr/lib64/`

**Comment by ingvar1995** [comment]
Strange, can't reproduce. Probably my openSUSE is too outdated. What version are you using and how did you install toxcore?

**Comment by Fak3** [comment]
openSUSE 42.2
add repo:
`zypper ar -f http://download.opensuse.org/repositories/home:/ecsos:/tox/openSUSE_Leap_42.2/ ecsos-tox`
install libs:
`zypper in libtoxencryptsave1 libtoxcore1 libtoxdns1`
install toxygen:
`pip3 install toxygen`
