### ISSUE TITLE
Current chat switching

### ISSUE THREAD

**Issue by Sorunome** [toxygen-project/toxygen#35]
The currently active chat is switching to something else if that user goes offline, however there is no indication of that anywhere. On the top it still displays the old person, though everything sends lands at a different person.
A similar thing can happen when a contact goes online.

**Comment by ingvar1995** [comment]
Is contact filtering enabled?

**Comment by Sorunome** [comment]
If you mean userlist sorting, i have it set to "Online first". Else, what do you mean?

**Comment by ingvar1995** [comment]
Yeah, I mean this. I will fix this bug tomorrow. Now Toxygen updates list of hidden users every time user goes online/offline, I will disable this for current (selected) user

**Comment by Sorunome** [comment]
i meant hte actual chat window showing the messages of the user that went offline and when i send something then suddenly e.g. groupbot says something with "command not found" as it sent that message there instead. The groupbot message still lands in the chat view thing.

**Comment by ingvar1995** [comment]
I understand what you mean. This is result of incorrect contacts list update.

**Comment by ingvar1995** [comment]
Fixed in develop branch
