### ISSUE TITLE
Cannot switch profile if you choose the wrong one as a default one.

### ISSUE THREAD

**Issue by Sopheus** [toxygen-project/toxygen#37]
I chose wrong profile (I forgot the password) and make it as a default one. Now Toxygen asks me the password I do not remember, and I cannot revert to profile selecting window.

**Comment by ingvar1995** [comment]
In 5bdbb28 I added possibility to reset default profile using ``toxygen --reset`` command. If you can't use latest develop version for some reason you have to delete toxygen.json file manually. You can found it on Linux in ``~/.config/tox``, on windows in ``AppData/Tox/``
