### ISSUE TITLE
Save toxygen.json in the app own folder

### ISSUE THREAD

**Issue by Qwash** [toxygen-project/toxygen#39]
Please Save toxygen.json in the same folder as the app

**Comment by ingvar1995** [comment]
Any reason for this? It's not required to make Toxygen portable. This file contains some Toxygen settings for computer, so there is no reason to save in app folder - this settings should be applied to all Toxygen's in system.

**Comment by Qwash** [comment]
Hello @ingvar1995 
I know that this file only contain the default profile settings
I don't need Toxygen to keep trace after I close it
beside this is not a good idea when different persons use Toxygen and share the same user {every one has his portable copy of Toxygen}
in that case they won't be able to set a default profile
Please keep every copy indpendent from the system so it's possible to add default profiles for different copies in the same user account.

**Comment by ingvar1995** [comment]
Done in 3194099
