### ISSUE TITLE
Avatar encryption

### ISSUE THREAD

**Issue by Qwash** [toxygen-project/toxygen#40]
Please encrypt the avatar

**Comment by ingvar1995** [comment]
I like this idea but I need more time to think how to implement this because proper implementation of this feature will break compability with other clients and won't be compliant with Tox client standard. Probably I will implement it as plugin.

**Comment by ingvar1995** [comment]
I'm closing this because of reasons described above. Avatars encryption functionality was implemented as plugin: [link](https://github.com/toxygen-project/toxygen_plugins/tree/master/AvatarEncryption)
