### ISSUE TITLE
Crash on "Set alias"

### ISSUE THREAD

**Issue by Baton34** [toxygen-project/toxygen#50]
Toxygen crash when i try to change friend alias.
os windows 8.1 x64
toxygen.exe ver 0.3.0
reproduce: right click on friend name in friends list, select "Set alias", toxygen crash.

**Comment by smaragdus** [comment]
I confirm the crash (**Toxygen** version **0.3.0** under _Windows 8 x64_), with **Toxygen** version **0.2.8** this never happened.

After crash and restart I see this warning message:

![toxygen 0 3 0 - 2017-07-10 - error - 001](https://user-images.githubusercontent.com/9025757/28013763-db654720-6572-11e7-8139-0b52af3b42e7.png)

**Comment by ingvar1995** [comment]
Fixed in 300b28b
