### ISSUE TITLE
could not start

### ISSUE THREAD

**Issue by Ygarr** [toxygen-project/toxygen#52]
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux unstable (sid)
Release:	unstable
Codename:	sid

0.4.0
$toxygen 
Traceback (most recent call last):
  File "toxygen/main.py", line 2, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "toxygen/loginscreen.py", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/libGL.so.1: undefined symbol: drmGetDevices2
Failed to execute script main

**Comment by ingvar1995** [comment]
Package from tox.chat?

**Comment by Ygarr** [comment]
From Debian Sid Repo.
Now it looks like:

$toxygen
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Smiley pack default loaded
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_equal.c:196:(_snd_pcm_equal_open) No slave configuration for equal pcm
ALSA lib pcm_equal.c:196:(_snd_pcm_equal_open) No slave configuration for equal pcm
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Segmentation fault

apt show toxygen
Package: toxygen
Version: 0.2.9-2
Priority: optional
Section: net
Maintainer: Yann Prive <encrypt@encrypt-tips.tk>
Installed-Size: 6,709 kB
Depends: python3, libtoxcore0, libtoxav0, libtoxencryptsave0, python3-pyside, python3-pyaudio
Homepage: https://github.com/toxygen-project/toxygen
Download-Size: 2,651 kB
APT-Manual-Installed: yes
APT-Sources: https://pkg.tox.chat/debian nightly/stretch amd64 Packages
Description: Tox client
 Powerful Tox client written in pure Python3.
