### ISSUE TITLE
Toxygen 0.4.1 - Fatal Error!

### ISSUE THREAD

**Issue by smaragdus** [toxygen-project/toxygen#54]
Hello,

After I updated **Toxygen** from version **0.4.0** to **0.4.1** it failed to start (on _Windows 8 x64_), I got an error message:
```
Fatal Error!
Failed to execute script main
```
Screen:
![toxygen 0 4 1 - 2018-01-28 - erreor - 001](https://user-images.githubusercontent.com/9025757/35478083-7e5ee406-03dc-11e8-8976-25a532c59a2b.png)

Regards

**Comment by ingvar1995** [comment]
Does previous toxygen version still work for you?

**Comment by smaragdus** [comment]
@ingvar1995 

> Does previous toxygen version still work for you?

Yes, **Toxygen** version **0.4.0** works just fine, I have never had any problems with this version.

**Comment by ingvar1995** [comment]
Sounds strange because accroding to traceback problem is in libtox.dll which is the same in both versions. And both versions were compiled using the same python.

**Comment by ingvar1995** [comment]
Try this binary: https://github.com/toxygen-project/toxygen/releases/download/v0.4.1/toxygen_windows2.zip

**Comment by smaragdus** [comment]
@ingvar1995 

Thanks for the fix- I can confirm that the second release of version 0.4.1 works fine under Windows 8. I am curious- what caused this error?

Several problems:

- For me 'Chat history' - 'Export as text' & 'Export as HTML' does not work at all- when I select the destination folder an empty file without extension is created. I cannot choose a name for the exported history either. For me exporting history doesn't work at all, at least under Windows.
- Right click in message panel- "Select all" does not select all the text but only the selected line. For me "Select all" should work as it works on any text editor.
- I think that message panel should not show only the time of the message but the date together with the time- currently one gets no idea about the actual date a message was received.
- Clicking on tray notification for new message just closes it- I think it would be better clicking if clicking 
 the notification opens the program window.
- You may make GitHub link in 'About program' clickable- clicking it opens the default browser.

**Comment by ingvar1995** [comment]
>I am curious- what caused this error?

I used latest pyinstaller version for compilation. And compiled binary didn't work on few OS for some unknown reason. Downgrade helped.

>For me 'Chat history' - 'Export as text' & 'Export as HTML' does not work at all

Fixed in b428bd5

>Right click in message panel- "Select all" does not select all the text but only the selected line.

Right click in text of message allows you to select single message only. If you want to select > 1 message, click on time/user name and select messages or select all via CTRL+A.

> think that message panel should not show only the time of the message but the date together with the time- currently one gets no idea about the actual date a message was received.

Or show date somewhere in the messages list, like in skype? or add tooltip? please open separate issue

>Clicking on tray notification for new message just closes it- I think it would be better clicking if clicking
the notification opens the program window.

>You may make GitHub link in 'About program' clickable- clicking it opens the default browser.

Good idea, please move to separate issue
