### ISSUE TITLE
Clickable links in 'About'

### ISSUE THREAD

**Issue by smaragdus** [toxygen-project/toxygen#55]
You may make the links in 'About' clickable for easier opening in default browser:

![toxygen 0 4 1 - 2018-01-30 - 002](https://user-images.githubusercontent.com/9025757/35580031-d970db22-05f0-11e8-94ce-4c6180f67cf4.png)

Optionally you may add link to [Issues](https://github.com/toxygen-project/toxygen/issues) for fast access to bugs reporting.

This was first suggested [here](https://github.com/toxygen-project/toxygen/issues/54).

**Comment by ingvar1995** [comment]
Implemented in 762eb89
