### ISSUE TITLE
Toxygen won't start on a machine with IPv6 disabled

### ISSUE THREAD

**Issue by StanLivitski** [toxygen-project/toxygen#59]
_Dear project team,_

I have tried to install Toxygen on a Ubuntu 16.04LTS machine and create a new user profile. Once I entered the user name, Toxygen quit with this message:

> `The function was unable to bind to a port. This may mean that all ports have already been bound, e.g. by other Tox instances, or it may mean a permission error. You may be able to gather more information from errno.`

That gave me no clue what was really going on until I finally ran Toxygen under `strace` to see the underlying error. It turned out that `toxcore` was trying to listen on an IPv6 port while my machine had IPv6 disabled.

Having looked at the source, I saw two issues:

1. By default, a new user profile has `ipv6_enabled` setting turned on without regard to IPv6's availability.

2. `ipv6_enabled` setting from the profile is not conveyed to the new `Tox` object in `tox_factory`, and thus has no effect. `Tox` object is created with IPv6 enabled by default, even if I edit the profile manually.

The following minimalistic patch worked for me with Toxygen 0.4.0. It should apply to the current version too, though the line numbers will be different:

**********************************************************
```
diff -cr toxygen-master/toxygen/profile.py toxygen-master1/toxygen/profile.py
*** toxygen-master/toxygen/profile.py	2017-07-21 11:39:10.000000000 -0400
--- toxygen-master1/toxygen/profile.py	2018-02-05 00:19:05.035738610 -0500
***************
*** 1426,1431 ****
--- 1426,1433 ----
      if settings is None:
          settings = Settings.get_default_settings()
      tox_options = Tox.options_new()
+     # see <https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h> lines 393-401
+     tox_options.contents.ipv6_enabled = settings['ipv6_enabled']
      tox_options.contents.udp_enabled = settings['udp_enabled']
      tox_options.contents.proxy_type = settings['proxy_type']
      tox_options.contents.proxy_host = bytes(settings['proxy_host'], 'UTF-8')
diff -cr toxygen-master/toxygen/settings.py toxygen-master1/toxygen/settings.py
*** toxygen-master/toxygen/settings.py	2017-07-21 11:39:10.000000000 -0400
--- toxygen-master1/toxygen/settings.py	2018-02-05 00:19:37.575899872 -0500
***************
*** 104,110 ****
          """
          return {
              'theme': 'dark',
!             'ipv6_enabled': True,
              'udp_enabled': True,
              'proxy_type': 0,
              'proxy_host': '127.0.0.1',
--- 104,110 ----
          """
          return {
              'theme': 'dark',
!             'ipv6_enabled': False,
              'udp_enabled': True,
              'proxy_type': 0,
              'proxy_host': '127.0.0.1',
```
**********************************************************

Note that I have changed the default for `ipv6_enabled` setting to `False` since I don't use it. That allows users to start Toxygen and change that setting later. If the team feels that `ipv6_enabled` should be `True` by default, there should be code that probes the underlying IPv6 stack and falls back to `False` when it's unavailable.

If you would like me to help writing that code, please let me know.

_Best regards,_
_Stan Livitski._

**Comment by ingvar1995** [comment]
Hello! Big thanks for your report and fix :smiley: I applied your patch to latest develop version in 98cc288
