### ISSUE TITLE
Clarify the toxcore/toxav fork and branch to be used when building Toxygen

### ISSUE THREAD

**Issue by StanLivitski** [toxygen-project/toxygen#60]
Hi Ingvar,

It seems to me that some of my audio/video problems with Toxygen might be caused by an old version of `toxcore` it used.

Instructions in `docs/install.md` suggest (in 2 places) that I should read and follow <https://github.com/irungentoo/toxcore/blob/master/INSTALL.md> when I install Toxygen. That leads me to fetching `toxcore` sources from <https://github.com/irungentoo/toxcore.git>, which defaults to the `master` branch of that repo. That branch hasn't been updated for over a year. There is another branch at `irungentoo/toxcore` as well:

> branch `master`: Latest commit dcf2aaa on Sep 28, 2016
> branch `new`: Latest commit ce60b9c on Oct 20, 2016

I am not sure which branch you used for your binary releases, but since the `.so` files are dated `Nov, 4  2016`, I suspect it might be `new`.

Besides that, there is [another fork of `toxcore` you are working on](https://github.com/ingvar1995/toxcore) with an active default branch

> branch `new-gc`: Latest commit d65b4cc on Feb 6, 2018

and several other branches.

Please let me know which fork and branch I should use with Toxygen `0.4.x` on Linux and update `docs/install.md` if needed.

Thank you,
Stan.

**Comment by ingvar1995** [comment]
Hi. For develop/master branches you need to install [this toxcore](https://github.com/irungentoo/toxcore/), master branch. New branch was completely broken last time I tried it. And my fork is required for using groupchat branch only (at least for now, soon I will push more branches with this toxcore required).
