### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5: undefined symbol: _Z12qTriangulateRK11QVectorPathRK10QTransformd

### ISSUE THREAD

**Issue by trDjango** [toxygen-project/toxygen#61]
I get the following error:
```
import cv2
ImportError: /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5: undefined symbol: _Z12qTriangulateRK11QVectorPathRK10QTransformd
```
I have no idea what to do. Thanks for your help.

**Comment by ingvar1995** [comment]
Hello! Please provide following info:
1) Your OS
2) How did you install Toxygen
3) How did you install opencv

**Comment by trDjango** [comment]
Hello,
1) my os : ubuntu 16.04
2) install method: Download source code from github
3) opencv install method: compile it from source code and install it(opencv version 3.4) .Not from pypi site.
Thanks for your help.

**Comment by ingvar1995** [comment]
Interesting. How did you install PyQt5? Have you tried to install/reqinstall ``libqt5opengl5`` package or PyQt5 itself? What version are you using? (``dpkg -s libqt5opengl5``)

**Comment by trDjango** [comment]
Hello ingvar1995,
I understand the problem.problem is not in toxygen.the problem is that when I install python3.6 into ubuntu, there are many bugs.I worked with python3.5.problem solved.
