### ISSUE TITLE
FileNotFound error when drag-and-drop file on Linux Mint Mate

### ISSUE THREAD

**Issue by Nokta-strigo** [toxygen-project/toxygen#65]
When I drag-and-drop file from file -manager to chat in Toxygen, the latter crashes with

> Traceback (most recent call last):
  File "toxygen/mainscreen_widgets.py", line 62, in dropEvent
  File "toxygen/mainscreen_widgets.py", line 73, in pasteEvent
  File "toxygen/profile.py", line 1119, in send_file
  File "toxygen/file_transfers.py", line 133, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/filename.ext\r\n'
Aborted

When I choose the same file from Toxygen window (by pressing on the clip image) it works fine.

Toxygen Version: 0.4.1 (https://github.com/toxygen-project/toxygen/releases/download/v0.4.1/toxygen_linux_64.tar.gz)

I believe the problem can be the unstripped '\r\n' simbols at the end of the filename, but I haven't checked it.

**Comment by ingvar1995** [comment]
Fixed in ce84cc5
