### ISSUE TITLE
Does any version work on Windows 32 bit?

### ISSUE THREAD

**Issue by Uzer1** [toxygen-project/toxygen#73]
Hello. Is there any version working on Windows X86 / 32 bit?

**Comment by ingvar1995** [comment]
Hello, latest version that had prebuilt binary for 32-bit windows was [0.2.8](https://github.com/toxygen-project/toxygen/releases/tag/v0.2.8). But it's still possible to run latest versions on 32-bit windows from sources

**Comment by Uzer1** [comment]
This one is working. I could not make it work from sources. It blinked and closed in the end.
