### ISSUE TITLE
Toxygen 0.4.3 - Windows

### ISSUE THREAD

**Issue by smaragdus** [toxygen-project/toxygen#77]
I am glad that a new version of Toxygen has been released. But I see that version [0.4.3](https://github.com/toxygen-project/toxygen/releases/tag/v0.4.3) was released for Linux only. So I would like to ask- will the latest version be released for Windows too?

**Comment by IngvarX** [comment]
Hi! Added precompiled binary for Windows too

**Comment by smaragdus** [comment]
@ingvar1995 

Great! I will download and test it tonight.

I hope that you will celebrate the 300th star with another release. ;)

Regards

**Comment by mva1985** [comment]
Thanks for the windows binary...  will test it out as well
