### ISSUE TITLE
OSError: libtoxav.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by saidemarlin** [toxygen-project/toxygen#79]
root@ubuntu:/usr/lib/toxygen# python3.6  main.py 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/lib/toxygen/libtox.py", line 35, in __init__
    self._libtoxav = CDLL('libtoxav.so')
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtoxav.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 487, in <module>
    main()
  File "main.py", line 483, in main
    toxygen.main()
  File "main.py", line 107, in main
    self.tox = profile.tox_factory()
  File "/usr/lib/toxygen/profile.py", line 1464, in tox_factory
    return Tox(tox_options)
  File "/usr/lib/toxygen/tox.py", line 99, in __init__
    self.AV = ToxAV(self._tox_pointer)
  File "/usr/lib/toxygen/toxav.py", line 25, in __init__
    self.libtoxav = LibToxAV()
  File "/usr/lib/toxygen/libtox.py", line 37, in __init__
    self._libtoxav = CDLL(util.curr_directory() + '/libs/libtoxav.so')
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/toxygen/libs/libtoxav.so: cannot open shared object file: No such file or directory
Exception ignored in: <bound method ToxAV.__del__ of <toxav.ToxAV object at 0x7fc3edf12a20>>
Traceback (most recent call last):
  File "/usr/lib/toxygen/toxav.py", line 50, in __del__
    self.libtoxav.toxav_kill(self._toxav_pointer)
AttributeError: 'ToxAV' object has no attribute 'libtoxav'
Exception ignored in: <bound method Tox.__del__ of <tox.Tox object at 0x7fc3edf12908>>
Traceback (most recent call last):
  File "/usr/lib/toxygen/tox.py", line 102, in __del__
    del self.AV
AttributeError: AV
root@ubuntu:/usr/lib/toxygen#

**Comment by sadiemarlin** [comment]
![image](https://user-images.githubusercontent.com/26355500/83979517-8d7d7800-a941-11ea-8003-fa13dcb9c490.png)

**Comment by saidemarlin** [comment]
when I click the Create button of the window of Log in,  then it is ...

**Comment by saidemarlin** [comment]
OS is Ubuntu 18.04

**Comment by IngvarX** [comment]
Hello, how did you install toxcore? I suppose that you used toktok toxcore which is not supported by Toxygen

**Comment by saidemarlin** [comment]
I installed toxcore in this way:  

You should get and install libsodium. If you have installed libsodium from repo, ommit this step, and jump directly to compiling toxcore:

git clone https://github.com/jedisct1/libsodium.git
cd libsodium
git checkout tags/1.0.3
./autogen.sh
./configure && make check
sudo checkinstall --install --pkgname libsodium --pkgversion 1.0.0 --nodoc
sudo ldconfig
cd ..

Compile toxcore
Then clone this repo, generate makefile, and install toxcore system-wide:

git clone https://github.com/irungentoo/toxcore.git
cd toxcore
autoreconf -i
./configure
make
sudo make install

doc address: https://github.com/irungentoo/toxcore/blob/master/INSTALL.md

**Comment by IngvarX** [comment]
Looks like deps required for building toxcore with AV are missing. Did you install all deps as described here: https://github.com/irungentoo/toxcore/blob/master/INSTALL.md#av ?

**Comment by saidemarlin** [comment]
root@ubuntu:/usr/lib/toxygen# apt-get install libopus-dev libvpx-dev pkg-config
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopus-dev is already the newest version (1.1.2-1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu2).
libvpx-dev is already the newest version (1.7.0-3ubuntu0.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 263 not upgraded.

root@ubuntu:/usr/lib/toxygen# apt-get install ncurses-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libncurses5-dev' instead of 'ncurses-dev'
libncurses5-dev is already the newest version (6.1-1ubuntu1.18.04).
0 upgraded, 0 newly installed, 0 to remove and 263 not upgraded.
root@ubuntu:/usr/lib/toxygen#

**Comment by IngvarX** [comment]
Do you have `libtoxav.so` file? Try `locate libtoxav.so`. Also make sure it was installed into `/usr/lib/` and not in `/usr/local/lib`

**Comment by saidemarlin** [comment]
I reinstalled the toxcore, now it works. Thanks a lot.

**Comment by IngvarX** [comment]
Glad it helped!
