### ISSUE TITLE
Fails to run: AttributeError: 'module' object has no attribute 'Slot'

### ISSUE THREAD

**Issue by yurivict** [toxygen-project/toxygen#9]
On FreeBSD  I am getting this error:
```
  File "/usr/local/lib/python2.7/site-packages/toxygen/list_items.py", line 387, in FileTransferItem
    @QtCore.Slot(int, float, int)
AttributeError: 'module' object has no attribute 'Slot'
```

**Comment by ingvar1995** [comment]
Toxygen is untested on FreeBSD. Do you use PySide or PyQt4?

**Comment by yurivict** [comment]
I am using PyQt4.

**Comment by ingvar1995** [comment]
Try with latest develop

**Comment by yurivict** [comment]
My PyQt4 is of the latest version 4.11.4.

**Comment by ingvar1995** [comment]
I mean with develop branch.

**Comment by ingvar1995** [comment]
I realized that some code required for FreeBSD and OS X support is missing. I will add it after some tests.

**Comment by yurivict** [comment]
Ok, thanks.

**Comment by ingvar1995** [comment]
I updated develop branch. Can you test it now?

**Comment by yurivict** [comment]
Now there are other problems:

* I use PyQt4 but it still wants PySide in styles/style.py and toxygen/tox_dns.py
* I had to change "import urllib.request" to "from urllib2 import Request"
* But it still fails with the error below:

```
$ toxygen 
Traceback (most recent call last):
  File "/usr/local/bin/toxygen", line 9, in <module>
    load_entry_point('Toxygen==0.2.3.0', 'console_scripts', 'toxygen')()
  File "/usr/local/lib/python2.7/site-packages/toxygen/main.py", line 418, in main
    toxygen = Toxygen()
  File "/usr/local/lib/python2.7/site-packages/toxygen/main.py", line 23, in __init__
    super(Toxygen, self).__init__()
TypeError: must be type, not classobj
```

I am not sure what is wrong.

**Comment by ingvar1995** [comment]
that's after python3 setup.py install? can you run it without installiation: python3 main.py?

**Comment by ingvar1995** [comment]
develop is updated again. hope it works (with python3 only)

**Comment by yurivict** [comment]
Python3 isn't supported on FreeBSD very well yet. python3-flavored PyQt conflicts with python2-flavored one. PyQt4 fails to build with python3 - syntax errors. I can install PyQt5, but toxygen wants PyQt4.

By choosing to be python3 only you effectively make it linux only. Is using python3 essential? If you need to use python3+qt4 currently it can't work on FreeBSD until python3 is supported better.

**Comment by ingvar1995** [comment]
What about PySide on FreeBSD? Toxygen was initially written in Python2.7 but later I migrated to Python3. Backport isn't too difficult I think.

**Comment by ingvar1995** [comment]
@yurivict any news? If nothing can be done I will close this.

**Comment by yurivict** [comment]
Yes, closing it for now.

**Comment by yurivict** [comment]
For the reference: some FreeBSD python-related ports can be changed to allow being used by both py2x- and py3x- at the same time. Currently they conflict. But the changes are quite extensive, and require full ports tree retest. I can't do this at this time, maybe later.
